import { readdirSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

const PLUGINS_DIR = "src/plugins";
const OUT_FILE = "src/generated-loader.ts";

export function discoverPlugins() {
  if (!existsSync(PLUGINS_DIR)) return [];
  return readdirSync(PLUGINS_DIR, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .filter(name => existsSync(join(PLUGINS_DIR, name, "index.ts")))
    .sort();
}

export function generateLoader() {
  const pluginDirs = discoverPlugins();

  const header = "// Auto-generated by scripts/generate-loader.mjs. Do not edit directly.\n// Re-run `npm run build` (or `npm run watch`) after adding/removing a plugin folder.\n";
  const pluginImports = pluginDirs.map(dir => `import "./plugins/${dir}/index";`).join("\n");
  const body = `${pluginImports}\nimport "./core/bootstrap";\n`;

  writeFileSync(OUT_FILE, `${header}\n${body}`)
  return pluginDirs;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const found = generateLoader();
  console.log(`[XtensionAPI | Build] Discovered ${found.length} plugin(s): ${found.join(", ") || "none"}`);
}
